name: Playwright Movie Check

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour (UTC)

jobs:
  run-playwright-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install
      - name: Run Playwright test
        run: npx playwright test
