name: Playwright Movie Check
on:
  repository_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual execution
  workflow_run:
    workflows: ["Playwright Movie Check"]
    types:
      - completed  # Retry if the last run fails

jobs:
  run-playwright-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (Suppress Console Output)
        run: |
          mkdir -p test-results
          npx playwright test --reporter=dot | tee test-results/playwright-console.log > /dev/null

      - name: Upload Playwright Console Output
        uses: actions/upload-artifact@v4
        with:
          name: playwright-console
          path: test-results/playwright-console.log

      - name: Upload Playwright Test Results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
