name: Trigger Playwright Workflow

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Test Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/playwright-movie-check.yml/dispatches \
          -d '{"ref":"main"}'
